# Generated by Django 5.1.7 on 2025-05-11 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_note_rewritten_content_note_summary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='標籤名稱')),
            ],
            options={
                'verbose_name': '標籤',
                'verbose_name_plural': '標籤',
                'db_table': 'tags',
            },
        ),
        migrations.RemoveField(
            model_name='note',
            name='category',
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': '筆記', 'verbose_name_plural': '筆記'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '使用者', 'verbose_name_plural': '使用者'},
        ),
        migrations.RemoveField(
            model_name='note',
            name='rewritten_content',
        ),
        migrations.RemoveField(
            model_name='note',
            name='summary',
        ),
        migrations.RemoveField(
            model_name='note',
            name='translated_content',
        ),
        migrations.RemoveField(
            model_name='note',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='user',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='note',
            name='parent',
            field=models.ForeignKey(blank=True, db_column='note_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='app01.note', verbose_name='父筆記'),
        ),
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='tempuser', max_length=100, unique=True, verbose_name='使用者帳號'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(verbose_name='筆記內容'),
        ),
        migrations.AlterField(
            model_name='note',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=200, verbose_name='筆記標題'),
        ),
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='app01.user', verbose_name='使用者'),
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='註冊時間'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='使用者郵箱'),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='加密後的密碼'),
        ),
        migrations.AlterModelTable(
            name='note',
            table='notes',
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
        migrations.CreateModel(
            name='NoteTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_tags', to='app01.note', verbose_name='筆記')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_tags', to='app01.tag', verbose_name='標籤')),
            ],
            options={
                'verbose_name': '筆記-標籤 關聯',
                'verbose_name_plural': '筆記-標籤 關聯',
                'db_table': 'note_tags',
                'unique_together': {('note', 'tag')},
            },
        ),
        migrations.AddField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(related_name='notes', through='app01.NoteTag', to='app01.tag', verbose_name='標籤'),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
