# Generated by Django 5.1.7 on 2025-05-25 05:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_insert_fake_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='note_images/', verbose_name='圖片')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app01.note', verbose_name='筆記')),
            ],
            options={
                'verbose_name': '筆記圖片',
                'verbose_name_plural': '筆記圖片',
                'db_table': 'note_images',
            },
        ),
    ]
